# Generated by Django 4.2.27 on 2026-01-26 09:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('target_type', models.CharField(choices=[('revenue', "Chiffre d'affaires"), ('invoices', 'Nombre de factures'), ('quotes', 'Nombre de devis'), ('conversion', 'Taux de conversion'), ('new_clients', 'Nouveaux clients')], default='revenue', max_length=20, verbose_name="Type d'objectif")),
                ('period', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name='Période')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mois')),
                ('quarter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valeur cible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='core.organization')),
            ],
            options={
                'verbose_name': 'Objectif de vente',
                'verbose_name_plural': 'Objectifs de vente',
                'ordering': ['-year', '-month', '-quarter'],
            },
        ),
        migrations.CreateModel(
            name='SalesKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_type', models.CharField(choices=[('revenue_total', 'CA Total'), ('revenue_average', 'CA Moyen par facture'), ('quotes_sent', 'Devis envoyés'), ('quotes_accepted', 'Devis acceptés'), ('conversion_rate', 'Taux de conversion'), ('invoices_sent', 'Factures émises'), ('invoices_paid', 'Factures payées'), ('payment_rate', 'Taux de paiement'), ('average_payment_delay', 'Délai moyen de paiement'), ('overdue_amount', 'Montant en retard'), ('new_clients', 'Nouveaux clients'), ('active_opportunities', 'Opportunités actives')], max_length=30, verbose_name='Type de KPI')),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valeur')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_kpis', to='core.organization')),
            ],
            options={
                'verbose_name': 'KPI Ventes',
                'verbose_name_plural': 'KPIs Ventes',
                'ordering': ['-date', 'kpi_type'],
                'unique_together': {('organization', 'kpi_type', 'date')},
            },
        ),
    ]
