# Generated by Django 4.2.27 on 2026-02-16 16:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_organization_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('category', models.CharField(choices=[('salary', 'Salaires'), ('rent', 'Loyer'), ('utilities', 'Services (eau, électricité, internet)'), ('supplies', 'Fournitures'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('equipment', 'Équipements'), ('maintenance', 'Maintenance'), ('taxes', 'Taxes et impôts'), ('insurance', 'Assurances'), ('other', 'Autres')], default='other', max_length=20, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('date', models.DateField(verbose_name='Date')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.organization')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
