# Generated by Django 4.2.27 on 2026-02-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_options_and_more'),
        ('accounts', '0003_user_active_organization_user_is_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.organization', verbose_name='Entreprise active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organization_admin',
            field=models.BooleanField(default=False, help_text="Peut gérer l'entreprise et ses membres", verbose_name='Admin entreprise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Peut accéder et gérer toutes les entreprises', verbose_name='Super administrateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organization', verbose_name='Entreprise'),
        ),
    ]
