# Generated by Django 4.2.27 on 2026-01-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='document_template',
            field=models.CharField(choices=[('classic', 'Classique'), ('modern', 'Moderne'), ('minimal', 'Minimaliste'), ('elegant', 'Élégant')], default='classic', help_text='Style des devis et factures PDF', max_length=20, verbose_name='Template documents'),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#1E40AF', max_length=7),
        ),
    ]
