# Generated by Django 4.2.27 on 2026-01-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_document_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='organization',
            name='capital',
            field=models.CharField(blank=True, help_text='Capital social (ex: 10 000)', max_length=50, verbose_name='Capital'),
        ),
        migrations.AddField(
            model_name='organization',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='rcs',
            field=models.CharField(blank=True, help_text='Registre du Commerce et des Sociétés', max_length=100, verbose_name='RCS'),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(blank=True, help_text='N° TVA intracommunautaire', max_length=20, verbose_name='N° TVA'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='siret',
            field=models.CharField(blank=True, max_length=14, verbose_name='SIRET'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
    ]
