# Generated by Django 4.2.27 on 2026-02-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Adhésion entreprise', 'verbose_name_plural': 'Adhésions entreprises'},
        ),
    ]
