# Generated by Django 5.1.4 on 2025-02-25

import apps.core.models
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('XOF', 'Franc CFA BCEAO (FCFA)'), ('XAF', 'Franc CFA BEAC (FCFA)'), ('USD', 'Dollar US ($)'), ('GBP', 'Livre Sterling (£)'), ('CHF', 'Franc Suisse (CHF)'), ('MAD', 'Dirham Marocain (DH)'), ('TND', 'Dinar Tunisien (DT)'), ('DZD', 'Dinar Algérien (DA)')], default='EUR', help_text='Devise utilisée pour les devis et factures', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='organizations/logos/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
