# Generated by Django 4.2.27 on 2026-01-25 17:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('category', models.CharField(choices=[('CLIENT', 'Client'), ('PROSPECT', 'Prospect'), ('PARTNER', 'Partenaire'), ('SUPPLIER', 'Fournisseur'), ('OTHER', 'Autre')], default='PROSPECT', max_length=20)),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='N° TVA')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'employés")),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='CA annuel')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Commercial assigné')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('civility', models.CharField(blank=True, choices=[('MR', 'M.'), ('MRS', 'Mme'), ('MS', 'Mlle')], max_length=5)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('category', models.CharField(choices=[('CLIENT', 'Client'), ('PROSPECT', 'Prospect'), ('PARTNER', 'Partenaire'), ('OTHER', 'Autre')], default='PROSPECT', max_length=20)),
                ('accepts_marketing', models.BooleanField(default=False, verbose_name='Accepte les communications marketing')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('mobile', 'Mobile')], default='email', max_length=20, verbose_name='Méthode de contact préférée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Commercial assigné')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company', verbose_name='Entreprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('probability', models.PositiveIntegerField(default=0, help_text='Default win probability percentage (0-100)')),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'opportunité")),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant')),
                ('probability', models.PositiveIntegerField(default=0, help_text='Probabilité de gain (0-100)', verbose_name='Probabilité (%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Date de clôture prévue')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Date de clôture réelle')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(blank=True, help_text='Comment avez-vous trouvé cette opportunité?', max_length=100, verbose_name='Source')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('next_step', models.CharField(blank=True, max_length=255, verbose_name='Prochaine étape')),
                ('lost_reason', models.TextField(blank=True, verbose_name='Raison de perte')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Commercial assigné')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.company', verbose_name='Entreprise')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.contact', verbose_name='Contact principal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.pipelinestage', verbose_name='Étape')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('file', models.FileField(upload_to='crm/documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='crm.tag'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='companies', to='crm.tag'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CALL', 'Appel'), ('EMAIL', 'Email'), ('MEETING', 'Réunion'), ('NOTE', 'Note'), ('TASK', 'Tâche'), ('DEMO', 'Démonstration'), ('PROPOSAL', 'Proposition'), ('OTHER', 'Autre')], default='NOTE', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='COMPLETED', max_length=20, verbose_name='Statut')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Date planifiée')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de rappel')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.company', verbose_name='Entreprise')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact', verbose_name='Contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity', verbose_name='Opportunité')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
    ]
