# Generated by Django 4.2.27 on 2026-01-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True, verbose_name='Adresse du client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_address',
            field=models.TextField(blank=True, verbose_name='Adresse du client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='crm.company', verbose_name='Entreprise'),
        ),
    ]
