# Generated by Django 4.2.27 on 2026-02-07 06:55

import apps.invoicing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_deleted_at_invoice_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit (JPG, PNG, max 5MB)', null=True, upload_to=apps.invoicing.models.product_image_path, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture de stock'), ('discontinued', 'Arrêté'), ('preorder', 'Précommande')], default='available', help_text='Statut de disponibilité du produit', max_length=20, verbose_name='Statut stock'),
        ),
    ]
