# Generated by Django 4.2.27 on 2026-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_add_product_image_and_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)')], default='XOF', max_length=3, verbose_name='Devise'),
        ),
    ]
